Repository clic2000/clic2000.fr, pull requests merged in 2020-11, with the labels that each got.

#6 Delete monsterpit mastodon fork
  artisanat.html
  assets/js/navigation-en.js
  assets/js/navigation-fr.js
  contact.html
  cooperative.html
  en/contact.html
  en/coop.html
  en/crafting.html
  en/index.html
  en/legals.html
  en/references.html
  en/services.html
  en/services/bigbluebutton.html
  en/services/mastodon.html
  en/services/nextcloud.html
  index.html
  mentions-legales.html
  references.html
  services.html
  services/bigbluebutton.html
  services/mastodon.html
  services/nextcloud.html
Labels: bug

#8 Remove tracking
  artisanat.html
  assets/js/tracking.js
  contact.html
  cooperative.html
  en/contact.html
  en/coop.html
  en/crafting.html
  en/index.html
  en/legals.html
  en/references.html
  en/services.html
  en/services/bigbluebutton.html
  en/services/mastodon.html
  en/services/nextcloud.html
  index.html
  mentions-legales.html
  references.html
  services.html
  services/bigbluebutton.html
  services/mastodon.html
  services/nextcloud.html
Labels: enhancement

#9 Push last changes to production
  artisanat.html
  assets/js/tracking.js
  contact.html
  cooperative.html
  en/contact.html
  en/coop.html
  en/crafting.html
  en/index.html
  en/legals.html
  en/references.html
  en/services.html
  en/services/bigbluebutton.html
  en/services/mastodon.html
  en/services/nextcloud.html
  index.html
  mentions-legales.html
  references.html
  services.html
  services/bigbluebutton.html
  services/mastodon.html
  services/nextcloud.html
Labels: bug, enhancement

#10 Last references
  assets/img/references/zef.jpg
  assets/img/references/zef.png
  en/references.html
  references.html
Labels: enhancement

#11 wider the main views
  artisanat.html
  contact.html
  cooperative.html
  en/contact.html
  en/coop.html
  en/crafting.html
  en/index.html
  en/legals.html
  en/references.html
  en/services.html
  en/services/bigbluebutton.html
  en/services/mastodon.html
  en/services/nextcloud.html
  index.html
  mentions-legales.html
  references.html
  services.html
  services/bigbluebutton.html
  services/mastodon.html
  services/nextcloud.html
Labels: enhancement

#12 Home ref
  assets/sass/styles.scss
  en/index.html
  index.html
Labels: enhancement
